apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-sentinel
spec:
  replicas: {{ .Values.replicas.sentinels }}
  template:
    metadata:
      labels:
        app: "{{ template "name" . }}"
        name: {{ template "fullname" . }}-sentinel
{{ include "labels.standard" . | indent 8 }}
    spec:
	  {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "fullname" . }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      affinity:
{{ toYaml .Values.sentinels.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}

      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}

      containers:
      - name: sentinel
        image: {{ include "redis-ha.imageFullName" . }}
        resources:
{{ toYaml .Values.resources.sentinel | indent 10 }}
        env:
          - name: SENTINEL
            value: "true"
          - name: REDIS_CHART_PREFIX
            value: {{ template "fullname" . }}-
        ports:
          - containerPort: 26379
