{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "kibana.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "kibana.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kibana.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}-kibana.{{ .Values.ingress.domainName }}
  rules:
  - host: {{ .Release.Name }}-kibana.{{ .Values.ingress.domainName }}
    http:
      paths:
        - path:
          backend:
            serviceName: {{ template "kibana.fullname" . }}
            servicePort: {{ .Values.service.externalPort }}

{{- end -}}
